// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJsx1iA__YhaAX8ub_lv-VgQ_G4PmiT0',
    appId: '1:954769418848:web:3dc185f6bcd1326ff77105',
    messagingSenderId: '954769418848',
    projectId: 'vanet-prototype1',
    authDomain: 'vanet-prototype1.firebaseapp.com',
    databaseURL:
        'https://vanet-prototype1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanet-prototype1.appspot.com',
    measurementId: 'G-MJL353WJBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArn4ivSsAnbvi75oOlkd8byNgEGTbAMQ0',
    appId: '1:954769418848:android:d394179fbd46f237f77105',
    messagingSenderId: '954769418848',
    projectId: 'vanet-prototype1',
    databaseURL:
        'https://vanet-prototype1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanet-prototype1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrO0rCA8S8WENz_ygCNLETv7SV9un1dw',
    appId: '1:954769418848:ios:907390bfbc5e6617f77105',
    messagingSenderId: '954769418848',
    projectId: 'vanet-prototype1',
    databaseURL:
        'https://vanet-prototype1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanet-prototype1.appspot.com',
    iosClientId:
        '954769418848-g8p3qgkjncc0vfniload3rkiqdvl45f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrO0rCA8S8WENz_ygCNLETv7SV9un1dw',
    appId: '1:954769418848:ios:907390bfbc5e6617f77105',
    messagingSenderId: '954769418848',
    projectId: 'vanet-prototype1',
    databaseURL:
        'https://vanet-prototype1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanet-prototype1.appspot.com',
    iosClientId:
        '954769418848-g8p3qgkjncc0vfniload3rkiqdvl45f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
